name: Compile and Upload Artifacts

on: [push]  # 触发工作流运行的事件，这里是 push 事件

jobs:
  build-and-upload:
    name: Compile and Upload
    runs-on: ubuntu-20.04  # 指定运行器环境

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # 检出你的代码到运行器

      - name: Set up Permissions for compile_mt7620.sh
        run: chmod +x ./compile_mt7620.sh  # 确保脚本具有执行权限

      - name: Execute compile_mt7620.sh
        run: ./compile_mt7620.sh  # 执行脚本

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware-binaries  # 构件的名称
          path: ./bin/targets/ramips/mt7620/*  # 指定要上传的文件或目录的路径
