name: miwifi-r3 compile

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Compile and Upload
    runs-on: ubuntu-20.04  # 指定运行器环境

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 检出你的代码到运行器

      - name: Set up Permissions for compile.sh
        run: chmod +x ./compile.sh  # 确保脚本具有执行权限

      - name: Execute compile.sh
        run: ./compile.sh  # 执行脚本

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries  # 构件的名称
          path: ./uploads/*  # 指定要上传的文件或目录的路径
